reorganize testing into single runonany image

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,92 +1,88 @@
-#!/usr/bin/bash
+#!/usr/bin/env bash
 
-x.images () {
-  x.client
-  x.server
+x.image() {
+	podman build -t runonany .
 }
 
-x.server () {
-	podman build -t ssh-server testdata/ssh-server
+x.clean() {
+	x.stop-servers
+	podman rmi runonany
 }
 
-x.client () {
-	podman build -t ssh-client .
+x.start-server() {
+	[[ -z "$1" ]] && echo "missing server number" && return 1
+	podman run -d -p "222$1:22" --rm --name "server$1" \
+		--hostname "server$1" runonany server
 }
 
-x.clean () {
-  x.stop
-	podman rmi ssh-server
+x.stop-server() {
+	[[ -z "$1" ]] && echo "missing server number" && return 1
+	podman stop "server$1"
 }
 
-x.start-ssh-server () {
-  [[ -z "$1" ]] && echo "missing server number" && return 1
-  podman run -d -p "222$1:22" --rm --name "ssh-server$1" \
-    --hostname "ssh-server$1" ssh-server
+x.start-servers() {
+	for i in {1..3}; do
+		if [[ -z "$(podman ps -q --filter "name=server$i")" ]]; then
+			x.start-server "$i"
+		fi
+	done
 }
 
-x.stop-ssh-server () {
-  [[ -z "$1" ]] && echo "missing server number" && return 1
-  podman stop "ssh-server$1"
+x.stop-servers() {
+	for i in {1..3}; do
+		x.stop-server "$i"
+	done
 }
 
-x.start-ssh-servers () {
-  for i in {1..3}; do
-    if [[ -z "$(podman ps -q --filter "name=ssh-server$i")" ]]; then
-      x.start-ssh-server "$i"
-    fi
-  done
+x.check-servers() {
+	[[ -z "$RUNONANY_TARGET" ]] && echo 'RUNONANY_TARGET' required && return 1
+	for i in {1..3}; do
+		podman run -it --rm runonany check "$RUNONANY_TARGET" "$i"
+	done
 }
 
-x.stop-ssh-servers () {
-  for i in {1..3}; do
-    x.stop-ssh-server "$i"
-  done
-}
-
-x.check-ssh-servers () {
-  [[ -z "$RUNONANY_TARGET" ]] && echo '$RUNONANY_TARGET' required && return 1
-  for i in {1..3}; do
-    podman run -it --rm ssh-client ssh "user@$RUNONANY_TARGET" -p "222$i" -o StrictHostKeyChecking=no -i /home/user/.ssh/user hostname
-  done
-}
-
-x.watch-client-runonany () {
-  [[ -z "$RUNONANY_TARGET" ]] && echo '$RUNONANY_TARGET' required && return 1
-  podman run -it --rm -e RUNONANY_TARGET="$RUNONANY_TARGET" ssh-client
+x.watch() {
+	[[ -z "$RUNONANY_TARGET" ]] && echo 'RUNONANY_TARGET' required && return 1
+	podman run -it --rm -e RUNONANY_TARGET="$RUNONANY_TARGET" runonany watch "$@" <&1
 }
 
 # --------------------- completion and delegation --------------------
-#      `complete -C foo foo` > `source <(foo bloated_completion)`
+
+# The following provides bash completion with `complete -C build build`
+# by deriving the names of the verbs for tab completion from those
+# beginning with x. above. No other argument completion is provided.
 
 while IFS= read -r line; do
-  [[ $line =~ ^declare\ -f\ x\. ]] || continue
-  COMMANDS+=( "${line##declare -f x.}" )
+	[[ $line =~ ^declare\ -f\ x\. ]] || continue
+	COMMANDS+=("${line##declare -f x.}")
 done < <(declare -F)
 mapfile -t COMMANDS < \
-  <(LC_COLLATE=C sort < <(printf "%s\n" "${COMMANDS[@]}"))
+	<(LC_COLLATE=C sort < <(printf "%s\n" "${COMMANDS[@]}"))
 
 if [[ -n $COMP_LINE ]]; then
-  line=${COMP_LINE#* }
-   for c in "${COMMANDS[@]}"; do
-    [[ ${c:0:${#line}} == "${line,,}" ]] && echo "$c"
-  done
-  exit
+	line=${COMP_LINE#* }
+	for c in "${COMMANDS[@]}"; do
+		[[ ${c:0:${#line}} == "${line,,}" ]] && echo "$c"
+	done
+	exit
 fi
 
 for c in "${COMMANDS[@]}"; do
-  if [[ $c == "$EXE" ]]; then
-    "x.$EXE" "$@"
-    exit $?
-  fi
+	if [[ $c == "$EXE" ]]; then
+		"x.$EXE" "$@"
+		exit $?
+	fi
 done
 
 if [[ -n "$1" ]]; then
-  declare CMD="$1"; shift
-  for c in "${COMMANDS[@]}"; do
-    declare cmd=$(command -v "x.$c")
-    if [[ $c == "$CMD" && -n "$cmd" ]]; then
-      "x.$CMD" "$@"
-      exit $?
-    fi
-  done
+	declare CMD="$1"
+	shift
+	for c in "${COMMANDS[@]}"; do
+		declare cmd
+		cmd=$(command -v "x.$c")
+		if [[ $c == "$CMD" && -n "$cmd" ]]; then
+			"x.$CMD" "$@"
+			exit $?
+		fi
+	done
 fi
